// ADITYAS MANDALA — PRODUCT DATA
// Colors sampled/refined from the brand reference mandala + brand doc palette.
// Ingredient amounts intentionally omitted (recipe protection policy).

const STORY_INTRO = `In the Rigveda, the Adityas are twelve solar deities — divine sons of Aditi, goddess of infinity and boundless space. Each governs one month of the year and embodies a distinct quality of solar light: vitality, wisdom, protection, nourishment, balance, healing, friendship, preservation, strength, craft, beauty, and joy. Unlike the vividly depicted gods of later Puranic art, the Adityas were, in their earliest Vedic conception, closer to principles than persons — forces holding cosmic order (ṛta) in place. We honor that origin: you will not find faces or figures here, only the color and position each deity has always held in the mandala. Our twelve turmeric formulas do not depict these deities. They are named in their honor, offered as a modern echo of qualities the Vedic poets first put into words three thousand years ago.`;

const PRODUCTS = [
  {
    id: "golden-rise",
    clock: 12,
    deity: "Vivasvat",
    name: "Golden Rise",
    color: "#C9940A",
    month: "Mārgaśīrṣa · Month I",
    tagline: "Natural Energy · Vitality · Oxygen Utilization",
    myth: "Vivasvat is named in the Rigveda as the first of the solar deities to be born — the primordial sun, father of Yama and Manu, the point from which all subsequent light unfolds. Later Vedic literature calls him the sun that first rose, the origin from which the cycle of days began.",
    bridge: "Golden Rise takes its name from Vivasvat not because it replicates any power attributed to him, but because the formula's purpose — natural energy, vitality, the body's first ignition of the day — echoes the role he holds at the very start of the solar cycle. We offer this formula in his honor, not in his place.",
    benefits: ["ATP production & cellular energy", "Oxygen utilization & endurance", "Hormonal vitality & libido", "Thermogenic circulation", "B12 energy metabolism"],
    taste: "Warm butterscotch-orange-ginger.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Gelatinized Maca Root", "Cordyceps Extract", "Vitamin B12 (Methylcobalamin)", "Ginger (5% Gingerols)", "BioPerine", "Organic Orange Juice Powder", "Organic Coconut Sugar"],
    precautions: ["Contains Cordyceps — a tree mushroom allergen.", "Caution advised for thyroid conditions (maca contains goitrogenic compounds).", "Not recommended for immunosuppressant users."],
    pairs: ["golden-mind", "golden-storm"]
  },
  {
    id: "golden-mind",
    clock: 1,
    deity: "Savitur",
    name: "Golden Mind",
    color: "#D9D4C4",
    colorText: "#3a3428",
    month: "Pauṣa · Month II",
    tagline: "Cognition · Focus · Stress Resilience",
    myth: "Savitur appears throughout the Rigveda as the deity of the sun's impelling light — the force that rouses the world to motion and, most famously, illuminates the intellect. The Gāyatrī Mantra, Vedic scripture's most revered verse, is addressed to him directly: a prayer not for warmth or harvest, but for clarity of mind.",
    bridge: "Golden Mind draws its name from this specific, well-attested domain — Savitur as illuminator of cognition — making it perhaps the most textually direct pairing in the entire mandala.",
    benefits: ["NGF & BDNF neuroregeneration", "Cortisol reduction (14–32% in trials)", "Executive function & focus", "Neuroinflammation reduction", "Cerebral circulation"],
    taste: "Bright lemon-ginger with golden warmth.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Lion's Mane Extract (8:1)", "Ashwagandha Root Extract (Dairy-Free)", "Ginger (5% Gingerols)", "BioPerine", "Organic Lemon Juice Powder", "Organic Coconut Sugar"],
    precautions: ["Ashwagandha: not recommended for thyroid disorders, autoimmune conditions, or if taking sedatives, SSRIs, or MAOIs.", "Contains Lion's Mane — a tree mushroom allergen.", "Not recommended during pregnancy.", "Not currently shipped to Denmark. Under Novel Food review in the EU/UK."],
    pairs: ["golden-rise", "golden-joy", "golden-rest"]
  },
  {
    id: "golden-flow",
    clock: 2,
    deity: "Pushan",
    name: "Golden Flow",
    color: "#8DC63F",
    month: "Māgha · Month III",
    tagline: "Digestive Health · Gut Microbiome · Absorption",
    myth: "Pushan is the Rigveda's guardian of paths and journeys — the deity invoked to guide travelers safely, to lead cattle to pasture, and to ensure that nourishment reaches its intended destination. He is sometimes called \"the one who sees all creatures\" for his role in guiding, not producing, sustenance along its route.",
    bridge: "Golden Flow is named for this idea of guided passage — Pushan as the one who ensures what enters the body actually reaches and nourishes it, echoed here in a formula built for digestive transit and absorption.",
    benefits: ["Feeds & balances gut microbiome", "Soothes and supports the gut lining", "Reduces bloating & gas", "Supports full nutrient absorption", "Improves digestive motility"],
    taste: "Warm ginger-fennel with bright citrus.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Organic Inulin (Chicory Root)", "Slippery Elm Bark Powder", "DGL Licorice", "Ginger (5% Gingerols)", "Fennel Seed Powder", "BioPerine", "Organic Lemon Juice Powder", "Organic Coconut Sugar"],
    precautions: ["DGL Licorice: avoid during pregnancy, hypertension, or if prone to fluid retention (oedema)."],
    pairs: ["golden-shield", "golden-balance"]
  },
  {
    id: "golden-balance",
    clock: 3,
    deity: "Vishnu",
    name: "Golden Balance",
    color: "#1E3A8A",
    month: "Phālguna · Month IV",
    tagline: "Hormone Balance · Stress Adaptation · Nervous System",
    myth: "In the Rigveda, Vishnu is invoked as the deity of three great strides that measure out the universe — a preserver of cosmic space long before his later, larger role in Puranic Hinduism as one of the tradition's most significant deities. His defining quality even in this earliest form is the maintenance of order and equilibrium across vast scales.",
    bridge: "Golden Balance takes his name in recognition of this preserving, equilibrium-holding quality — offered as a formula for hormonal and nervous-system balance, in deep respect toward a principle central to Hindu theology.",
    benefits: ["Cortisol reduction & stress resilience", "Hormone balance (men & women)", "Alpha-wave calm focus without sedation", "Adrenal support & fatigue reduction", "Blood sugar stability"],
    taste: "Mild floral-citrus with herbal warmth.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Shatavari Root Extract (Organic)", "Rhodiola Rosea (3% Rosavins)", "L-Theanine", "Magnesium Glycinate", "BioPerine", "Organic Lemon Juice Powder", "Organic Coconut Sugar"],
    precautions: ["Shatavari: not recommended during pregnancy, for hormone-sensitive conditions, or alongside HRT.", "Rhodiola: not recommended for bipolar disorder. Not with MAOIs; use caution with SSRIs."],
    pairs: ["golden-flow", "golden-rest"]
  },
  {
    id: "golden-build",
    clock: 4,
    deity: "Dhata",
    name: "Golden Build",
    color: "#A0522D",
    month: "Caitra · Month V",
    tagline: "Collagen Synthesis · Skin, Hair & Nails · Bone",
    myth: "Dhata — from the Sanskrit root dhā, \"to place\" or \"to establish\" — is named among the Adityas as the deity of creation and right ordering: the one who establishes and arranges the elements of the world into form. Later tradition associates him closely with the crafting of living structure.",
    bridge: "Golden Build carries his name for this reason: a formula centered on collagen synthesis and structural support, named for a deity whose earliest textual role is the establishing of form itself.",
    benefits: ["Stimulates collagen & elastin synthesis", "Strengthens hair, skin & nails", "Supports bone density & connective tissue", "Whole-food Vitamin C per serving", "100% vegan structural support"],
    taste: "Light citrus-floral with subtle earthiness.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Acerola Cherry (25% Vit C)", "Amla Fruit (45% Vit C)", "Silica from Bamboo (70%)", "Nettle Leaf Extract", "Biotin", "Zinc Bisglycinate", "BioPerine", "Organic Coconut Sugar"],
    precautions: ["Biotin: stop 48–72 hours before scheduled lab work — it can interfere with certain test results.", "Zinc may interact with tetracycline or fluoroquinolone antibiotics — separate doses by at least 2 hours."],
    pairs: ["golden-body", "golden-glow"]
  },
  {
    id: "golden-body",
    clock: 5,
    deity: "Aryaman",
    name: "Golden Body",
    color: "#9E1B32",
    month: "Vaiśākha · Month VI",
    tagline: "Recovery · Joint Comfort · Anti-Inflammation · Mobility",
    myth: "Aryaman is named in the Rigveda as the deity of noble bonds — guardian of hospitality, customs, and the ties formed between companions, particularly those forged through shared undertaking and effort. Later tradition also links him to ancestral rites and the honor owed between generations.",
    bridge: "Golden Body takes his name for this connection to effort honorably given and honorably recovered from — a formula built for the recovery and joint comfort that follow real physical exertion.",
    benefits: ["Reduces exercise soreness & accelerates recovery", "Cartilage protection & joint comfort", "Dual-pathway anti-inflammatory support", "Muscle relaxation without sedatives", "Prostaglandin balance"],
    taste: "Tart cherry — a warm rose-gold hue in water.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Tart Cherry Extract", "Boswellia (65% AKBA)", "Magnesium Glycinate", "Ginger (5% Gingerols)", "BioPerine", "Organic Lemon Juice Powder", "Organic Coconut Sugar"],
    precautions: ["Use caution alongside blood thinners — this formula combines multiple ingredients with mild antiplatelet activity.", "Use caution alongside NSAIDs.", "Stop use 2 weeks before any scheduled surgery."],
    pairs: ["golden-storm", "golden-build"]
  },
  {
    id: "golden-years",
    clock: 6,
    deity: "Mitra",
    name: "Golden Years",
    color: "#2F5233",
    month: "Jyeṣṭha · Month VII",
    tagline: "Longevity · NAD+ · Cellular Regeneration · Telomeres",
    myth: "Mitra is one of the oldest and most consistently honored Adityas — the Rigveda's deity of covenant, friendship, and the binding trust between parties who keep their word to one another. He is closely paired with Varuna throughout Vedic literature, together upholding the moral order (ṛta) of the cosmos.",
    bridge: "Golden Years is offered in his honor as a formula for longevity and cellular renewal — an alliance, in modern form, between the body and time itself.",
    benefits: ["NAD+ restoration via Nicotinamide Riboside", "Sirtuin activation & DNA repair support", "Telomere length maintenance", "Autophagy & cellular cleanup", "Anti-fatigue & immune regulation"],
    taste: "Warm, earthy, golden with reishi depth.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Nicotinamide Riboside (NR)", "Resveratrol (98% Trans)", "Reishi Mushroom (30% Polysaccharides)", "Astragalus (70% Polysaccharides)", "Ginger (5% Gingerols)", "BioPerine", "Organic Coconut Sugar"],
    precautions: ["Resveratrol: not recommended alongside blood thinners, hormone therapy, or liver medications.", "Contains Reishi — a tree mushroom allergen.", "Not recommended for immunosuppressant users.", "May raise serum lithium levels — important if you take lithium.", "Not recommended for hormone-sensitive conditions. Stop 2 weeks before surgery."],
    pairs: ["golden-shield", "golden-glow"]
  },
  {
    id: "golden-shield",
    clock: 7,
    deity: "Varuna",
    name: "Golden Shield",
    color: "#1B8A99",
    month: "Āṣāḍha · Month VIII",
    tagline: "Immunity · Antioxidant Defence · Respiratory Resilience",
    myth: "Varuna is among the most exalted deities of the Rigveda — sovereign of cosmic and moral law (ṛta), keeper of the celestial waters, and the deity most closely associated with maintaining the boundary between order and chaos in the universe. His waters are the encompassing, protective expanse that holds the world within its proper limits.",
    bridge: "Golden Shield takes his name for this protective, boundary-maintaining role — a formula built for immune defense, offered in honor of a deity whose oldest recorded function is the preservation of order against disorder.",
    benefits: ["Antiviral anthocyanin support", "May reduce cold duration", "Whole-food Vitamin C", "Zinc for T-cell immune production", "Cytokine regulation"],
    taste: "Bright berry-lemon with gentle ginger warmth.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Elderberry Extract (Standardized)", "Acerola Cherry (25% Vit C)", "Zinc Bisglycinate", "Ginger (5% Gingerols)", "BioPerine", "Organic Lemon Juice Powder", "Organic Coconut Sugar"],
    precautions: ["Elderberry: not recommended for immunosuppressant users.", "Not recommended for autoimmune conditions (MS, lupus, RA, Hashimoto's)."],
    pairs: ["golden-years", "golden-flow", "golden-glow"]
  },
  {
    id: "golden-storm",
    clock: 8,
    deity: "Indra",
    name: "Golden Storm",
    color: "#6B3FA0",
    month: "Śrāvaṇa · Month IX",
    tagline: "Peak Performance · Pre-Workout · Power · Endurance",
    myth: "Indra is the Rigveda's most frequently invoked deity — wielder of the vajra (thunderbolt), lord of storms, and the god most closely tied to strength, victory, and the release of monsoon rains after struggle. He is traditionally counted among the Adityas in the later, twelve-fold Puranic enumeration this mandala follows.",
    bridge: "Golden Storm is named for this association with peak exertion and controlled power — a pre-performance formula honoring a deity whose central myths are, quite literally, about unlocking maximum force at the right moment.",
    benefits: ["Natural nitric oxide & circulation support", "Power output & ATP regeneration", "Reduced lactic acid buildup", "Clean, moderate natural caffeine focus", "Exercise inflammation management"],
    taste: "Bold beet-orange-ginger — earthy and energizing.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Beetroot Extract (2% Nitrates)", "Beta-Alanine", "Caffeine (Green Tea)", "Ginger (5% Gingerols)", "BioPerine", "Organic Orange Juice Powder", "Organic Coconut Sugar"],
    precautions: ["Contains natural caffeine (~50mg, about half a cup of coffee).", "Do not use with Viagra, Cialis, or other ED medications — the nitrate content can cause a dangerous drop in blood pressure.", "Beta-alanine may cause a harmless tingling sensation (paresthesia).", "Not recommended for heart conditions or within 6 hours of sleep."],
    pairs: ["golden-body", "golden-rise", "golden-rest"]
  },
  {
    id: "golden-rest",
    clock: 9,
    deity: "Tvashtr",
    name: "Golden Rest",
    color: "#3E4C5E",
    month: "Bhādrapada · Month X",
    tagline: "Deep Sleep · Nighttime Recovery · Nervous System Restoration",
    myth: "Tvashtr is the Rigveda's divine artisan — the craftsman deity who shapes forms, forges the vajra Indra wields, and works, according to the hymns, largely unseen: his craft occurring in the quiet spaces others do not witness.",
    bridge: "Golden Rest carries his name for this reason — a nighttime formula honoring a deity whose defining quality, uniquely among the twelve, is craft performed in darkness and silence, its results visible only afterward.",
    benefits: ["May reduce sleep onset time", "Deeper, more restorative sleep quality", "Nighttime cortisol reduction support", "Muscle relaxation without sedatives", "Supports cellular repair during sleep"],
    taste: "Warm tart cherry-vanilla with earthy depth.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Tart Cherry Extract", "Magnesium Glycinate", "Ashwagandha Root Extract (Dairy-Free)", "Passionflower Extract (4:1)", "L-Theanine", "BioPerine", "Organic Vanilla Powder", "Organic Coconut Sugar"],
    precautions: ["Ashwagandha: not recommended for thyroid disorders or alongside sedative medications.", "Passionflower: not recommended during pregnancy.", "Do not drive or operate machinery after use.", "Not recommended alongside prescription sedatives or benzodiazepines.", "Not currently shipped to Denmark. Passionflower import classification under verification in Japan."],
    pairs: ["golden-mind", "golden-storm", "golden-joy"]
  },
  {
    id: "golden-glow",
    clock: 10,
    deity: "Savitar",
    name: "Golden Glow",
    color: "#C2438C",
    month: "Āśvina · Month XI",
    tagline: "Skin Radiance · Beauty · Collagen · UV Defence",
    myth: "Savitar shares an etymological root with Savitur — both derive from the sun's impelling, life-giving light — and in some traditions the two names refer to the same deity viewed at different moments of the solar cycle: Savitar specifically associated with the transitional light of dawn and dusk.",
    bridge: "Golden Glow takes this name for its association with transitional, radiant light — offered as a formula for skin health, honoring the moments of the day when the sun's presence is most visibly, beautifully in motion.",
    benefits: ["Multi-pathway collagen synthesis support", "Deep cellular skin hydration", "Antioxidant UV & pollution defence", "Natural skin brightening", "Supports elasticity and fine-line reduction"],
    taste: "Bright, tart hibiscus-rosehip with sweet berry notes.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Acerola Cherry (25% Vit C)", "Organic Rosehip Powder", "Tremella Mushroom Extract", "Organic Hibiscus Flower Powder", "Grape Seed Extract (95% OPCs)", "BioPerine", "Organic Coconut Sugar"],
    precautions: ["Contains Tremella — a tree mushroom allergen.", "Use caution alongside blood pressure medications (hibiscus can have a mild blood-pressure-lowering effect)."],
    pairs: ["golden-build", "golden-shield", "golden-years"]
  },
  {
    id: "golden-joy",
    clock: 11,
    deity: "Bhaga",
    name: "Golden Joy",
    color: "#E3A83B",
    month: "Kārtika · Month XII",
    tagline: "Mood · Serotonin Support · Emotional Resilience · Neuroplasticity",
    myth: "Bhaga is the Rigveda's deity of good fortune, prosperity, and rightful share — the one who distributes what is due and, in doing so, delivers not just material wealth but the felt experience of abundance and delight. His month, Kārtika, contains Diwali, the festival most closely associated with joy prevailing over darkness.",
    bridge: "Golden Joy closes the mandala in his honor — a formula for mood and emotional resilience, named for the deity whose entire domain is the felt experience of things going well.",
    benefits: ["Serotonin support via saffron", "NGF & BDNF neuroplasticity support", "Adaptogenic emotional resilience", "Natural mood support via cacao", "Neuroinflammation reduction"],
    taste: "Rich cacao-citrus with a whisper of saffron.",
    ingredients: ["Turmeric (95% Curcuminoids)", "Saffron Extract (2% Safranal)", "Lion's Mane Extract (8:1)", "Rhodiola Rosea (3% Rosavins)", "Organic Cacao Powder", "BioPerine", "Organic Lemon Juice Powder", "Organic Coconut Sugar"],
    precautions: ["Saffron: not recommended during pregnancy. Not recommended with MAOIs, SSRIs, or SNRIs (risk of serotonin syndrome).", "Contains Lion's Mane — a tree mushroom allergen.", "Rhodiola: not recommended for bipolar disorder.", "Under Novel Food review in the EU/UK (Lion's Mane). California: cacao is subject to Prop 65 heavy-metal testing requirements."],
    pairs: ["golden-mind", "golden-balance", "golden-rest"]
  }
];

function getProduct(id) {
  return PRODUCTS.find(p => p.id === id);
}
